### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by saihaj** [ScribeDAO/retweet#12]
This is a meta issue to track different phases
- [X] Login with Discord and and assign categories to summaries (#3) 
- [ ] Scribe should submit for review and Knowledge seeker or above will approve it for retweet
- [ ] Ability to assign requests to users
- [ ] Ability for users to submit requests for content to be summarized
- [ ] Migrate notion data to requests table here
- [ ] Expose endpoint for users to retrieve data from our DB and use it to make frontends #6
